name: Test checks

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:


jobs:
  tests:
    strategy:
      matrix:
        test-os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.test-os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install depedencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python unit_tests.py
          python integration_tests.py